Разбил код на модули и добавил презентер
htmlacademy-ecmascript/1878499-big-trip-simple-18 pull request #3
Opened 2022-08-18 14:18 UTC by RomanMalinovskiy

2022-08-18 15:07 UTC, VAnastasia requested changes

2022-08-18 15:07 UTC, VAnastasia commented on src/presenter/trip-content-presenter.js
> +import EventsListView from '../view/sort-event-view.js';
С путями что-то не то, должно быть '../view/events-list.js'

2022-08-18 15:07 UTC, VAnastasia commented on src/presenter/trip-content-presenter.js
> +import SortView from '../view/event-point-view.js';
а здесь '../view/sort-events-view.js'

2022-08-19 19:32 UTC, RomanMalinovskiy commented on src/presenter/trip-content-presenter.js
> +import EventsListView from '../view/sort-event-view.js';
исправил

2022-08-19 19:32 UTC, RomanMalinovskiy commented on src/presenter/trip-content-presenter.js
> +export default class TripEventsPresenter {
исправил

2022-08-19 19:32 UTC, RomanMalinovskiy commented on src/presenter/trip-content-presenter.js
> +import SortView from '../view/event-point-view.js';
исправил

2022-08-20 07:22 UTC, merged